### PR TITLE
Fix time in /queue and /last-played

### PR DESCRIPTION
**Pull request by Qarray**
Fix for issue #61. Added a `replaceTimeZones` function in the javascript and changed a `<span>` to `<time>` because /queue has it like this.

### CODE REVIEW

**Comment by Bevinsky** [comment]
Looks good to me. I guess the best feature would be if the timestamp included the date if it was older than a day (both on server and client side), but if you want to add that is up to you.

If you don't want to, just say so and I'll merge it.

**Comment by Qarray** [comment]
Ok! Added a table display to the list so everything would align properly. Looks like this without it

image
The appearance changed slighly because of this, but I think it should be fine.

I've never really used Laravel, so I'd rather not do the server side implementation for now.

**Comment by Bevinsky** [comment]
How does that look when the window is scaled down, for example on mobile devices?

**Comment by Qarray** [comment]
Doesn't look too good on tablets actually, sorry about that. I'll change it in a moment

**Comment by Qarray** [comment]
Now looks like this
tablet
mobile1
mobile2

**Comment by Bevinsky** [comment]
Odd behavior. The padding between the time and metadata varies wildly:




And on some there's odd wrapping:

**Pull request merged**
